DROP DATABASE IF EXISTS userInfoDB
CREATE DATABASE userInfoDB
USE userInfoDB
CREATE TABLE userInfo (
    id INT AUTO_INCREMENT NOT NULL,
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60) NOT NULL,
    email VARCHAR(80) NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE passWords (
id INT AUTO_INCREMENT NOT NULL,
content VARCHAR(100) NOT NULL,
userID INT(10) NOT NULL,
PRIMARY KEY (id)
);